# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: dev/blesi
description: > # this means to ignore newlines until "baseurl:"
  This is Patrick Blesi's personal site. It holds his blog and
  shares some info about him.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patrick.ble.si" # the base hostname & protocol for your site, e.g. http://example.com
owner:
  name: Patrick Blesi
  email: patrick@ble.si
  twitter: pblesi
  github: pblesi

# Number of posts to show on home page
paginate: 5

permalink: /:categories/:title

collections:
  projects:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

kramdown:
  parse_block_html: true

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - vendor

github: [metadata]
